feat: consult-product
7-Seven-Up/megastore-frontend pull request #18
Opened 2024-09-28 17:56 UTC by NicoAntu

Hecha la lógica para obtener y mostrar todos los productos de la base de datos.

El único problema que me estaría dando es que no enseña las imágenes correctamente, nose si es problema mío cuando cree los productos o si es algo del código, estaría bien revisar eso.

2024-09-28 18:04 UTC, delgadomatias commented on a
Y este archivo? Se supone que no debería estar acá.

2024-09-28 18:05 UTC, delgadomatias commented on src/modules/products/components/ProductCard.tsx
> +interface ProductCardP {
Estaría mejor un nombre mas descriptivo. Algo como:
```suggestion
interface ProductCardProps {
```

2024-09-28 18:06 UTC, delgadomatias commented on src/modules/products/components/ProductCard.tsx
> +            ( <p>No image avaiable</p>)}
1. Esta mal escrito, debería ser **available**
2. Se supone que no es un atributo opcional por lo tanto siempre debería existir, no te debería dar este problema.

2024-09-28 18:12 UTC, delgadomatias commented on src/modules/products/components/ProductList.tsx
Algunas variables están de mas:
1. El pageSize ya te lo retorna la data creo.
2. Lo mismo con el totalPages, no es un calculo que el front debería hacer. Ya viene en la respuesta.

Ademas, estaría bueno algo mas elaborado para indicar que se están cargando los productos. Tenemos componentes como un [Skeleton](https://nextui.org/docs/components/skeleton) que estilandolo podrías darle formas como las tarjetas.

2024-09-28 18:13 UTC, delgadomatias commented on src/modules/products/components/ProductList.tsx
> +        <button
Esta bueno tener estos botones sin embargo disponemos de un componente [Pagination](https://nextui.org/docs/components/pagination) el cual es mucho mas lindo y funcional.
Ya se hizo implementaciones de este componente, tenes que leer las cosas ya hechas en el codigo.

2024-09-28 18:15 UTC, delgadomatias commented on src/modules/products/hooks/useGetProducts.ts
> +        pageSize: 12,
Porqué sobreescribis su valor? Podrías hacerlo mas arriba y decirle que sea igual a 12.

2024-09-28 18:20 UTC, delgadomatias commented on src/modules/products/interfaces/product-response.interface.ts
> +export interface ProductResponse {
Para tipar estas interfaces yo mismo he creado una interfaz genérica llamada PaginatedResponse en donde le pasas un genérico, que en este caso seria Product, quedaría algo asi:


```suggestion
import { PaginatedResponse } from "@/shared/interfaces/pagination/paginated-response.interface.ts";

export interface Product {
  productId: string;
  name: string;
  description: string;
  price: number;
  imageURLS: string[];
  stock: number;
  color: string;
  sizeName: string;
  variantOfName: string;
}

export type ProductResponse = PaginatedResponse<Product>;
```

2024-09-28 18:21 UTC, delgadomatias commented on src/modules/products/interfaces/product.interface.ts
Bien, separarlo en otro archivo puede estar bien. Si queres podes hacerlo como te comente arriba.

2024-09-28 18:22 UTC, delgadomatias commented on src/shared/pages/ProductsPage.tsx
Hmmm, estaría bueno que pongas imágenes para tener una preview de lo que hiciste. Pero acá este div esta pelado y no va a estar alineado con los otros elementos como la Navbar.

2024-09-28 18:25 UTC, delgadomatias requested changes
Bien Nico, te dejé algunos comentarios.

Estaría bueno que muestres con unas screenshots que no cuestan nada para ver lo que hiciste. Hay algunos escenarios en los cuales ya existen implementaciones en nuestro código y tenias que amoldarla a tu problema, sugiero que revises mas lo que hemos hecho. De todas formas es un buen comienzo, seguí así! :+1:

2024-09-28 18:27 UTC, delgadomatias commented on src/modules/products/components/ProductCard.tsx
> +            ( <p>No image avaiable</p>)}
Ah y otra cosa, la URL debería ser /products/{productId}

2024-09-28 18:42 UTC, NicoAntu commented on a
Ese archivo me salto cuando agregue los archivos para hacer el commit, cuando lo realice me salto esta advertencia:

"warning: in the working copy of 'a', LF will be replaced by CRLF the next time Git touches it"

Nose cuando se creó porque solo trabaje sobre el producto, nose si antes tenía otro nombre o si siquiera existía

2024-09-28 18:47 UTC, NicoAntu commented on a
sí tenía un nombre anterior y otra ubicación avísame donde se encontraba así la coloco donde corresponde, y si no debería existir la borro.

2024-09-28 19:07 UTC, NicoAntu commented on src/shared/pages/ProductsPage.tsx
con lo hecho en el primer commit muestra esta preview :
![Captura de pantalla 2024-09-28 160707](https://github.com/user-attachments/assets/77164341-8b9b-454d-98ad-7af68f9ab8ba)

2024-09-28 19:26 UTC, delgadomatias commented on src/shared/pages/ProductsPage.tsx
Bueno, vez que esa sección no esta alineada con el Navbar? deberías arreglarlo.
Estaría bueno que copies algún diseño por ahí, en la cual muestres la imagen completa y luego por debajo el nombre y el precio, con alguna fuente mas grande.

2024-09-29 00:42 UTC, ValeLattanzi approved these changes

2024-09-29 03:13 UTC, merged