Feat/recover password
7-Seven-Up/megastore-frontend pull request #7
Opened 2024-09-14 23:01 UTC by ValeLattanzi

# Changes:
* Added an option to recover user's password by email

2024-09-14 23:43 UTC, delgadomatias commented on src/modules/user/schemas/recover-password.schema.ts
Estas validaciones son iguales a la del backend? No recuerdo haber visto tantas validaciones así. 
No tendría sentido sobrecargar de validaciones el front si luego el back no las realiza también.

2024-09-14 23:45 UTC, delgadomatias commented on src/modules/user/schemas/send-email.schema.ts
Me hace ruido el mensaje de error cuando la constraint de required falla, estas diciendo que el e-mail es invalido, cuando esto mismo podes indicar en la otra constraint que usas expresiones regulares.
Como lo venimos trabajando, podes dejarlo como un string vacio al error del required, ya que por defecto se pinta el input de rojo.

2024-09-14 23:49 UTC, delgadomatias commented on src/modules/user/user.service.ts
No mandaría la new password y el token por query params. Mejor por body.

2024-09-14 23:55 UTC, delgadomatias commented on src/shared/pages/user/RecoverPasswordPage.tsx
Me imagino que acá tuviste problemas con Typescript que te decía que los parametros podrían ser undefined, por eso pusiste el "!"
Que sucede si no tengo ningun userId ni token en la URL? Probaste?

2024-09-14 23:55 UTC, delgadomatias commented on pnpm-lock.yaml
Esto no se debería subir al repositorio.

2024-09-15 00:33 UTC, ValeLattanzi commented on src/shared/pages/user/RecoverPasswordPage.tsx
Lo puse así porque por lógica nunca va a terminar llegando el usuario a esa página si no es a través del mail

2024-09-15 00:39 UTC, Fedesan14 requested changes

2024-09-15 02:37 UTC, Fedesan14 commented on src/modules/user/schemas/recover-password.schema.ts
No es que no tenga sentido, las validaciones deberian ser las mismas porque estas vienen de los requerimientos solicitados por el usuario, si esa validacion la hacemos en el front:

1. Deberia ser porque lo solicita el cliente y
2. También tendría que estar en el backend ya que es el servidor

2024-09-15 02:38 UTC, Fedesan14 commented on src/shared/pages/user/RecoverPasswordPage.tsx
Ojo con esto, al ser un parámetro por URL, el usuario -que siempre tenes que pensar que es lo más boludo posible- puede borrar eso para "probar" a ver qué pasa

2024-09-21 15:17 UTC, Fedesan14 requested changes

2024-09-21 15:17 UTC, Fedesan14 commented on src/modules/user/user.service.ts
>  };
Sobre esto tengo algunos comentarios

1. La URL definida en el backend es `/api/v1/users/recover-password/{userId}` por lo que esto no va a funcionar
2. De donde sacamos el userId? Si el usuario perdio la contraseña, nunca va a poder ingresar a su cuenta por lo que jamas el frontend va a tener una respuesta que le proporcione el ID del usuario y, además, el usuario NUNCA va a saber su ID (no debería). Por lo que pensaría diferente como se hace esto, quizás en vez de usar el userId podemos usar el correo electrónico o el mismo token que generamos para luego encontrar el usuario y setearle su nueva contraseña.

Y se me ocurre algo que podemos mandar en el correo de recuperación que es "Nunca compartas tu token con nadie"

2024-09-21 15:17 UTC, Fedesan14 commented on src/modules/user/user.service.ts
>          email,
Esto lo podriamos sacar ya que vamos a enviar el email por body

2024-09-21 15:17 UTC, Fedesan14 commented on src/modules/user/components/RecoverPasswordForm.tsx
> +      userId: "",
Si al final no vamos a usar el userId, esto deberiamos sacarlo

2024-09-23 23:05 UTC, ValeLattanzi commented on src/modules/user/user.service.ts
>  };
Acabo de cambiar el endpoint para que se comuniquen por el mail del usuario que es único para no exponer el id, pero el tema del mensaje "Nunca compartas tu token con nadie" vos crees que sea necesario? Porque en sí el token no lo manipula directamente el usuario

2024-09-24 15:55 UTC, Fedesan14 approved these changes
Muy buen laburo Latta, te felicito!

2024-09-24 17:28 UTC, EzeSosa approved these changes

2024-09-26 00:46 UTC, merged