feat: authenticate users
7-Seven-Up/megastore-frontend pull request #8
Opened 2024-09-15 01:32 UTC by delgadomatias

Lo que se aborda en esta PR es la autenticación del usuario en el lado del cliente.
Cuando un usuario ingresa correctamente su nombre de usuario y su contraseña se hace una petición al backend y cuando tenemos la respuesta y es correcta hacemos dos cosas: seteamos en un estado global lo que nos llego y redirigimos al usuario a la pagina de inicio. 

Ahora bien, con respecto al **estado global** se utilizó [Zustand](https://zustand-demo.pmnd.rs/), el cual es una alternativa a Redux y me parece mucho mas sencilla para implementar y que ustedes puedan entender, su curva de aprendizaje es mucho más baja.
Se implementó el middleware **persist** para que tengamos un punto de acceso fuera de la aplicación asi podemos persistir los datos, en nuestro caso, de la autenticación incluso si la aplicación se reiniciara. **¿Como logra Zustand esto?** lo que hace es setear en el localStorage (por defecto) los atributos que nosotros tengamos en el store. Esto es, se guarda el accessToken, el userId y el rol del usuario en el localStorage.

Entonces... puedo modificar los datos ahí guardados y entonces se modificaría el estado global, pero tengamos en cuenta que no hay que pensar en el Front como la fuente de la verdad, porque es fácilmente manipulable. Si se modifican los datos hay que estar protegidos del lado del servidor, entonces, si los datos son incorrectos esto fallaría, como es en nuestro caso.

Me gustaria darle una buena mencion al componente **RoleBasedVisibility** que nos permitira renderizar componentes basados en roles. Por ejemplo, en una proxima funcionalidad tenemos que tener un panel de administración, justamente utilizaríamos dicho componente para mostrar un botón que nos rediriga ahí.

# Visualización
![ezgif-7-3ffdc9498c](https://github.com/user-attachments/assets/786614fa-5218-4c68-b4fc-ab8c13829d74)

2024-09-15 02:01 UTC, EzeSosa requested changes
Me encantó la explicación  y la inclusión de Zustand, no la conocía para nada. Gran laburo como siempre. Te dejé un par de boludeces nomás

2024-09-15 02:01 UTC, EzeSosa commented on src/shared/lib/httpClient.ts
> +  const excludedPaths = ["/auth/signin", "/auth/signup"];
Esto quizás podría moverse a una constante así contamos también a futuro las otras rutas a las cuales no deberíamos agregar el header (el activar usuario, el recuperar contraseña)

2024-09-15 02:46 UTC, Fedesan14 commented on src/modules/auth/auth.service.ts
> +    null,
Se tiene que poner el null si o si porque despues tiene que especificar el tercer parámetro que son los headers. Typescript no te permite hacer referencia a los parametros como kotlin que podes hacer algo como

post(URL, headers = headers)

Si o si tienes que hacer

post(URL, body, headers)

2024-09-15 03:05 UTC, Fedesan14 approved these changes

2024-09-17 20:15 UTC, EzeSosa approved these changes

2024-09-17 21:58 UTC, Fedesan14 approved these changes

2024-09-17 21:58 UTC, merged